### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by naarkhoo** [mahdikhashan/aparat-python#1]
Thanks for sharing this repository - is there any way to upload videos through the API ?

**Comment by mahdikhashan** [comment]
Not yet. But I'm trying to find some way if I get time.

**Comment by mohsen-hassani** [comment]
Hello @mahdikhashan, I've added the upload video functionality to the repository. Please take a look at my PR.
Thanks

**Comment by mahdikhashan** [comment]
@mohsen-hassani Hey, thanks for your commitment, it's now merged.
